### ISSUE TITLE
zhaoyu个人简介

### ISSUE THREAD

**Issue by yzhaoyu** [casbin/Talent2021#1]
我是重庆大学微电子与通信工程学院的硕士研究生雍昭宇，我个人对Golang和Python比较熟悉，今年四月份到九月份在腾讯实习，主要负责QQ后台的开发业务，使用Golang'进行开发；我使用Golang已经有一年半的时间了，希望能够参与Casbin项目的开发工作。

**Comment by hsluoyz** [comment]
感谢你对Casbin感兴趣，我们目前正在招募Gsoc2021的学生候选人，如果你对Casbin感兴趣，可以积极参与进来，先从解决一些社区的问题入手，提交1个小的pr，让社区看到你的实力，然后会有导师和你联系。
